name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  CI:
    runs-on: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade pip & tools
        run: |
          python -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Run detect.py
        run: |
          python detect.py --weights yolov7.pt --conf-thres 0.25 --nosave

      - name: Run detect_and_track.py
        run: |
          python detect_and_track.py --weights yolov7.pt --conf-thres 0.25 --nosave
